USE sc2;

CREATE OR REPLACE PIPELINE games
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/games/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE games FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE OR REPLACE PIPELINE uniquekind
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/uniquekind/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE uniquekind FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE OR REPLACE PIPELINE players
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/players/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE players FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE OR REPLACE PIPELINE playerstats
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/playerstats/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE playerstats FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE OR REPLACE PIPELINE buildcomp
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/buildcomp/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE buildcomp FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

CREATE OR REPLACE PIPELINE compvecs
AS LOAD DATA LINK aws_s3 'esports-demo-backup/csv/compvecs/*'
SKIP DUPLICATE KEY ERRORS
INTO TABLE compvecs FORMAT CSV
FIELDS TERMINATED BY '\t'
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n';

START ALL PIPELINES;