FROM floydhub/torch:7-py3.6

# install deps
RUN apt-get update
RUN apt-get install -y libzstd1-dev

# install StarData & TorchCraft
RUN git clone https://github.com/TorchCraft/StarData.git /StarData 
RUN cd /StarData && git submodule update --init
RUN cd /StarData/TorchCraft && pip install .

WORKDIR /code

code:
    COPY src src

build:
    FROM +code

    RUN cmake src

    # cache cmake temp files to prevent rebuilding .o files
    # when the .cpp files don't change
    RUN --mount=type=cache,target=/code/CMakeFiles make

    RUN ./replay-processor
    SAVE ARTIFACT replay-processor

test:
    COPY +build/replay-processor /bin/replay-processor
    COPY testdata /testdata
    RUN /bin/replay-processor /testdata/*

docker:
  COPY +build/replay-processor /bin/replay-processor
  # ENTRYPOINT ["/bin/replay-processor"]
  SAVE IMAGE singlestore/gaming-telemetry:replay-processor